version: "3"
services:
  app:
    container_name: app_SmartActR
    restart: always
    build: ./backend/
    command: >
      bash -c
      "
      pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple &&
      if ! find ./migrations; then python manage.py db init; fi &&
      python manage.py db migrate &&
      python manage.py db upgrade &&
      gunicorn -w4 -b :5000 --log-level=debug manage:app"
    volumes:
      - ./backend/:/code
    expose:
      - "5000"
    depends_on:
      - mysql
    networks:
      - mysql_network
      - web_network
  mysql:
    container_name: mysql_SmartActR
    image: mysql:5.7
    volumes:
      - "/home/lighthouse/mysql_SmartActR/:/var/lib/mysql"
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{password}} #填写你的数据库密码
      - MYSQL_DATABASE=SmartActR
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - mysql_network

  app_manager:
    container_name: app_SmartActR_manager
    restart: always
    build: ./manager_backend/
    command: >
      bash -c
      "pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple &&
      gunicorn -w4 -b :6000 --log-level=debug manage:app"
    volumes:
      - ./manager_backend/:/code
      - "/home/lighthouse/project/SmartActR/manager_backend/application/static/:/application/static"
    expose:
      - "6000"
    depends_on:
      - mysql
    networks:
      - mysql_network
      - web_network

  nginx:
    container_name: nginxserver_SmartActR
    restart: always
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./manager_backend/application/static:/static
      - ./config/nginx:/etc/nginx/conf.d
      - ./manager_frontend/dist:/code
      - ./crt:/crt
    depends_on:
      - app
      - app_manager
    networks:
      - web_network
  

networks:
  mysql_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  static-volume: