version: "3"
services:
  app:
    container_name: app_SmartActR
    restart: always
    build: .
    command: >
      bash -c
      "
      pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple &&
      if ! find ./migrations; then python manage.py db init; fi &&
      python manage.py db migrate &&
      python manage.py db upgrade &&
      gunicorn -w4 -b :5000 --log-level=debug manage:app"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - my_app_network
  mysql:
    container_name: mysql_SmartActR
    image: mysql:5.7
    volumes:
      - "/home/lighthouse/mysql_SmartActR/:/var/lib/mysql"
    env_file: .env
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= {{password}} #替换为你配置的密码
      - MYSQL_DATABASE=SmartActR
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - my_app_network

networks:
  my_app_network:
    external: true

volumes:
  static-volume: